version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-actions:
        patterns:
          - "docker/*"
    commit-message:
      prefix: "ci"
