# Copyright 2022-2025 The MathWorks, Inc.

name: Build, Test and Publish the Dockerfile

# Trigger this workflow either manually or when a new change is pushed to the
# repo (except .md files)
on:
  workflow_dispatch:
  push:
    # Trigger the workflow is the Dockerfile or any file under tests/ is modified
    paths:
      - "Dockerfile"
      - "tests/*"
      - "tests/utils/**"
      - ".github/workflows/build-test-publish.yml"
      - "!**.md"
  schedule:
    # Run at 00:00 on every Monday (1st Day of the Week)
    - cron: "0 0 * * 1"

env:
  IMAGE_BASE_NAME: ghcr.io/${{ github.repository }}/matlab
  LICENSE_FILE_PATH: ${{ github.workspace }}/license.lic

jobs:
  build-test-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        matlab-release:
          - R2025b
          - R2025a
          - R2024b
          - R2024a
          - R2023b
          - R2023a
          - R2022b
          - R2022a
          - R2021b
          - R2021a
          - R2020b

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image locally
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          load: true
          build-args: |
            MATLAB_RELEASE=${{ matrix.matlab-release }}
          tags: |
            ${{ env.IMAGE_BASE_NAME }}:${{ matrix.matlab-release }}

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi

      - name: Generate license file
        run: echo '${{ secrets.MATLAB_LICENSE_FILE }}' > ${{ env.LICENSE_FILE_PATH }}

      - name: Test container
        env:
          IMAGE_NAME: ${{ env.IMAGE_BASE_NAME }}:${{ matrix.matlab-release }}
        working-directory: tests
        run: python -m unittest -v

      - name: Push the image to ghcr.io
        env:
          MATLAB_RELEASE: ${{ matrix.matlab-release }}
        run: |
          LOWERCASE_RELEASE=${MATLAB_RELEASE,,}
          UPPERCASE_RELEASE=${LOWERCASE_RELEASE^}
          docker tag ${{ env.IMAGE_BASE_NAME }}:${MATLAB_RELEASE} ${{ env.IMAGE_BASE_NAME }}:${LOWERCASE_RELEASE}
          docker tag ${{ env.IMAGE_BASE_NAME }}:${MATLAB_RELEASE} ${{ env.IMAGE_BASE_NAME }}:${UPPERCASE_RELEASE}
          docker push --all-tags ${{ env.IMAGE_BASE_NAME }}
